# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d65e042af7671d7ddee599913665ebf1c431361e49736141dfe3d0814949c16bd84102a946a2ff4b6642ecf2b210fa9d1b99855459fbee32b126b0628f1cd99
  gmail_username: <%= ENV["GMAIL_USERNAME"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
  cloudinary_url: <%= ENV["CLOUDINARY_URL"] %>


test:
  secret_key_base: bc6d777e050fe525098fd9f807bd39e81ab64fe8df4780bbc427added7446f39c677fe889ab6297f488872bbc37370fd9db9f90264015fa1c4dca788ecbe99e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  gmail_username: <%= ENV["GMAIL_USERNAME"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
  cloudinary_url: <%= ENV["CLOUDINARY_URL"] %>
